### ISSUE TITLE
Add authentication checks to endpoints

### ISSUE THREAD

**Issue by VigdisIS** [dotkom/vengeful-vineyard#124]
When a punishment is marked as paid by a user, it is not posted to the backend, and just says "null".

We currently have access to the authenticated user, so we should be able to post the name of the logged in user who approved the punishment as paid.

**Comment by Terbau** [comment]
I edited the original issue to have a new purpose. In order to achieve the original idea, we need to include the authorization token in the header on all post requests and make sure the user is authenticated. Implementing `verified_by` and other similar fields will be easy once this is done. It makes sense to do this at the same time.
